---
title: Charlotte Museum of History
author: CRSansom
date: '2019-04-29'
slug: Charlotte-Museum-of-History
categories: []
tags:
  - R Markdown
---

<h1> Contents <h1>
<h3>About	 <br>
Areas of Focus	 <br>
Data at a Glance	<br>
Constraints	 <br>
Audience Analytics	 <br>
Demographic Segmentation	 <br>
Recommendations	<br>
Appendix	 <br>
<h3>










<h1>About<h1>
<h3>Our focus for this project is the Charlotte Museum of History which is located in the Plaza Midwood community in Charlotte, North Carolina.  The Museum has a large main gallery with rotating exhibits covering Charlotte history from the Revolutionary War through today.  There are other preserved historic structures on the property, most notably, the Hezekiah Alexander House which is a restored farmhouse built in 1774 and is the oldest surviving structure in Mecklenburg County.
<p>
While the Museum raises some money through ticket sales, the vast majority of funding comes from members and other personal and corporate donations.  There are several events hosted at the Museum throughout the year with the main fundraising efforts focused on the Colonial Gem event held each May.  Since 2000 the museum has raised roughly $12.5 million from corporate and personal donations and the museum currently has almost 200 active members.<h3> 



<h1>Areas of Focus<h1>

<h3>After talking to the Charlotte Museum of History’s Development Director, it was apparent that the museum has a few areas that could be individually targeted for improvement.  First, there is no information being collected about visitors to the museum, neither for members nor non-members.  The efforts around tracking ticket purchases for visitors to the museum is virtually nonexistent.  While there is a payment system to process the museum entry fees and gift shop purchases, there is minimal data collection occurring at either of these points of contact.  Further, the transaction data from these ticket sales is not made available to the museum for analysis.  From our view this is a missed opportunity to learn more about the people who choose to come to the museum and find out what brought them there and why.  Similar issues are apparent for Membership tracking, where there is no data being kept about how often a particular member visits the museum.  
<p>
Second, the museum should enhance its approach to social media.  While the museum has a very well laid out webpage (charlottemuseum.org), there is no effort to collect data about visitors to the website.  The museum also has both a Facebook and an Instagram page.  Similarly, there have been no efforts to use the data on who has ‘Liked’ the social media pages or published content to identify demographic data on who is interested in the museum.  This is another point of contact with potential donors that is not being fully utilized to find out more about these individuals.  
<p>
A third area that could be improved is donor data.  The Museum uses Talisma Fundraising software which was not designed with Museum operations in mind creating limitations in terms of what kind of data can be stored as well as gaps in the ability to access the information in a sensible way.  Further complicating this is that there is a lack of training on the software amongst Museum staff so very few people on site know how to extract data at all.  There are some data quality issues with the member database where in some cases there is data missing or conflated as well as some duplicate entries present.  Additionally, there is not an easy way to discern corporate members from individual members in the current database.
<p>
The Charlotte Museum of History has a lot of good data available to it in addition to many loyal donors that are dedicated to seeing the Museum succeed.  However, the landscape in Charlotte is crowded with similar institutions seeking donations from civic-minded organizations and individuals from art museums to cultural centers and there is some competition for donor funding amongst these institutions.  The goal of our project is to focus on the areas outlined above to help the Charlotte Museum of History cultivate its data in a way that will increase its competitive advantage and increase donor activity.<h3>

<h1>Data at a Glance<h1>

<h3>There were three main sources of data used for this project.  First, we were given four excel spreadsheets containing gift and member datasets from the museum’s Talisma software system.  The ‘Donor History by Category Dataset’ is used by the Museum for purposes of gift tracking and lead generation.  This spreadsheet consists of 2785 lines of data with 28 columns of data.  The spreadsheet includes donor name, address info and amounts of donations and when the donations were given.  The data includes 2726 unique addresses and 2513 unique gifts.  The ‘Every Member Ever’ dataset consists of 2140 rows and 19 columns.  This dataset has 2140 unique account IDs, 1982 unique addresses, and includes information on everyone who has been a member of the Museum and their contact information.  The ‘Every Gift Ever’ dataset contains a list of every gift that has been made and recorded by the Museum and includes names, addresses and dates and the amount of each gift as well as other information about what capital campaign the gift was tied to, etc.  This dataset has 9208 lines each representing a single gift to the Museum with 27 columns of data.  There are 2783 unique accounts who have given gifts to the Museum and one account has made 33 separate gifts to the Museum.  The final dataset is the ‘No Gifts Data’ spreadsheet and this includes all member of the Museum who have never given a gift.
<p>
The second source of data we used in our project was Facebook data that was provided to us by the Museum.  The Facebook data consisted of Excel spreadsheets with data describing page likes and posts drawn from the Museum’s Facebook page.   The first dataset we used is the ‘Lifetime Post Consumers by Type’ which contains historical datapoints describing the total posts published by the museum and contains data on the number of people that clicked on the post.  The data in this spreadsheet covers the 2015-2018 timeframe. There are 15 variables in this dataset and, in total, there are around 3000 rows of data.  Second, we used the ‘Daily Like Sources and Mentions’ dataset from Facebook in order to examine the likes and posts reached by the followers.  The data can be configured to show likes by post, date and comments.  Lastly, we used the ‘Page Engagement Key Metrics’ dataset which includes 153 rows and 139 columns showing multiple classifications of click views and metrics.  This dataset provides cumulative page views by follower and the variables are tracked across year, month and quarter.  We used R Studio and the shiny library package to create the Facebook Visualizations and the Shiny application.
<p>
The third source of data we used for our project is the Census Dataset containing demographic information on the census statistical area of Charlotte.  This dataset was pulled at the census tract level which is a sub-county level and includes counties in North and South Carolina.  The key variables we pulled from the census dataset are median income, place of work, children under 18 in household, school enrollment, education attained, and median gross rent.  We used the CensusData python library to access the US Census Bureau’s API using Python.  We then pulled from ac5 of the Census, data from 2017 since that is the latest data available.  The code looped over the counties included in the Charlotte Metro area (Mecklenburg, York, Union, Gaston, Cabbarus, Iredell, Rowan, Cleveland, Lancaster, Lincoln, Stanley and Chester) and pulled census data for the target variables we listed above.  We then pulled the GEOID for each census tract from the APIs response.  The census data then had to be matched with a shapefile in order to be graphed in Tableau. Our code to retrieve census data was obtained through a web connector (see appendix) that allowed us to pull the 2010 census shape files for North and South Carolina.  Then these tracts were trimmed down so that only the counties in our Charlotte Metro region were included.  In order to find the GEOID for our current donors we used the censusgeocode Python package.  This Python code cleaned up all of the non-Charlotte region addresses and then concatenated the relevant addresses together into a format that could be used by the censusgeocode package.  The code then pulled the GEOID for each row with columns returning value of error dropped from the final output.  We then loaded the generated files into Tableau to create our visualization of Donor Demographics.<h3>
<h1>Constraints<h1>
<h3>In addition to the limitations with the Museum’s data collection and software which we discussed in our introduction, there are other issues we encountered with the data we used for this project that are worth noting.  Firstly, as we discussed, the Museum is not quite to the Proactive stage of data management.  This created some constraints as pulling donor data for these purposes is outside of the normal use of the software system.  Second, there were limitations in using Google Analytics as the available data is not sufficient for conducting any meaningful analysis.  The website tracking ID was not set up so this potentially useful data is unavailable.  Third, the Facebook data we were able to attain is qualitative and we were unable to pull data on follower demographics.  As such, we used the data that was available to us to conduct the following Audience and Demographic analysis for the Museum.<h3>
<h1>Audience Analytics<h1>
<h3>Using the Facebook data provided by the Museum, we created a series of Visualizations using R Studio, Shiny and Tableau in order to help analyze the data on who is liking the Museum’s posts and pages.  The first visualization (Exhibit A) we produced is ‘Page Engagement by City.’  It is obvious that the largest source of page likes and views is the city of Charlotte, but some of the other results are somewhat interesting and can potentially help us identify areas that the museum should focus some of it’s fundraising efforts based on interest.  For example, some of the larger areas represented in the Facebook data are Concord, Gastonia, Greensboro, Indian Trail, Matthews, Mooresville, Marvin as well as Rock Hill and Fort Mill in South Carolina. 
<p>
Next, we used the Facebook data to create another visualization (Exhibit B) for ‘Page Engagement by Gender and Age.’  This chart shows the total number of likes on the y-axis and different age groups of both Female and Male Facebook users on the x-axis.  There are a couple of interesting findings about Facebook users that can be gleaned from this data.  One is that more women are actively liking the Museum’s social media posts than men.  And second, the majority of likes are coming from women aged 35-44 years of age.  This data can also be used to create campaigns targeted at this demographic as more engaged users are probably more likely to donate or take part in a museum event.  
<p>
A Third visualization (Exhibit C) we produced with the Facebook data is a chart showing the Museum’s organic reach vs. paid reach.  This chart clearly shows that there is more value in the Museum’s organic page postings and stories vs. marketing efforts that are paid for.  Since the average paid marketing posts are not yielding significant results in terms of reach.  It is our opinion that the paid posts are not worth pursuing as the organic reach is many times that of the paid reach.
<p>
 Lastly, we created an application with R Studio’s Shiny package that will allow the museum to analyze their Facebook data.  This application is located at the following link https://ibrokhim-sadikov.shinyapps.io/Abebhjg/ and can also offer some useful insights.  The shiny application contains the Facebook data and has several interactive features that the user can use to conduct analysis using the data.  There are dropdowns for the user to choose a dataset (either city or museum) then select what dependent and independent variables the user wants to use to examine the data.  The output tabs at the top of the application are Data, Summary Statistics, Histograms, Scatter Plot, Correlations, Model, and Residuals.  These tabs together show the relevant statistics for the dependent and independent variables selected and offer some other insights.  The entire report can then be exported by pdf for the user to save down.  Hopefully these tools and insights will enhance the Museum’s Social Media presence and add to its competitive advantage.<h3>  
<h1>Demographic Segmentation<h1>
<h3>We used the museum gift dataset coupled with the sensustrack data to create a few visualizations showing donor counts across several input variables including: income, education and families with children under 18.  These visualizations show some clusters (exhibits D, E, F) where there is a correlation between these two variables suggesting they are useful to be used in our model.   We then took these variables from our data and mapped them using Tableau.  The first map image we came up with (exhibit G) shows the Charlotte Metro area broken into 4 clusters based off of demographic data from the census dataset.  The clusters that are colored blue and yellow are not areas that have the strongest set of variables and the areas highlighted orange and red are areas that have strong correlated demographics to our set.  The second picture (Exhibit G) has the number of donors overlaid on the clusters.  The donor bubbles are displayed so the larger the size of the bubble, the larger the count of donors in that cluster.  Based on these visualizations we can see that the majority of donors are located in the Red and Orange regions to the South of Charlotte with another cluster in the Lake Norman area to the North.  These visualizations can be useful as the museum can target these areas with similar demographic clusters to the ones that provide the highest number of donors.<h3>  
<h1>Recommendations<h1> 
<h3>Based on our research, there are a number of recommendations that we would like to make to the Charlotte Museum of History.  First, we would recommend that the Museum start collecting and cataloging data on museum visits and ticket sales so that they will have more meaningful data about who is using the museum.  Second, from the visualizations we produced with the donor data, we recommend that the Museum focus advertising efforts on the red/orange areas to the North of Charlotte that do not have a large population of current donors and yet have similar demographics to areas that already have high donor numbers.  Third, we recommend that the Museum host events off-site in some of the target areas we have identified to try and reach those favorable demographic populations.  Fourth, the Museum might want to tailor efforts to the 30-50-year-old age group as identified in our Facebook analysis, and focus marketing more on women.  Lastly, as mentioned earlier, the paid Facebook posts are not generating as much traffic in terms of likes as the organic posts, so we believe that these are not an ideal use of the Museum’s marketing budget.  In order to gain more insight into the Facebook activity the Museum might use the Shiny application to further analyze the social media landscape.  A city that is growing as quickly as Charlotte has a need to reconnect with its history and the Museum is an essential element in that process.  By leveraging the data that the museum already has and enhancing some data collection processes, the Charlotte Museum of History should be able to use enhance its competitive advantage.<h3>  

Appendix

•	Census data was obtained through a web connector constructed by Mark Evans from his blog “I Like Big Bytes”
•	http://ilikebigbytes.com/index.php/2016/09/07/mapping-census-tracts-in-tableau/
•	bigbytes.mobyus.com/tableau/censustractshapeswdc11.aspx
•	Obtaining the GEOID for our donors was accomplished using the censusgeocode python package
•	https://pypi.org/project/censusgeocode/
